### ISSUE TITLE
Tracking issue for Wayland development progress

### ISSUE THREAD

**Issue by ghost** [input-leap/input-leap#1251] opened 2021-11-04 23:45 UTC
> This issue has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/issues/1251
> 
> Issue created on: 2021-08-16 by @shymega
> Issue last updated on: 2021-09-18

This issue is for Wayland development to be documented, and updates given on the progress of adding Wayland support to Barrier.

---

> Commented on: 2021-08-16 by @shymega

@p12tic Could you please push a branch to the repo with your local Barrier development work when you can, please? That way we can have contributions for Wayland support.

---

> Commented on: 2021-09-18 by @akutoku

The **libei** project seems to be very interesting in the context of barrier. It seems to be what implementation of barrier working with Wayland compositors needs. Seeing that it's a part of libinput project, seems to be a safe choice to use because it is very likely that this will be used by majority if not all Wayland compositors.

https://gitlab.freedesktop.org/libinput/libei
https://github.com/whot/barrier/tree/wip/ei

**Comment by MYanello** [comment] 2022-05-18 12:48
It seems that they've figured this out for waynergy https://github.com/r-c-f/waynergy

Keyboard mapping is a bit wonky, and only works as a client but it's a start and let's us keep using barrier on wayland for now.

**Comment by donjan** [comment] 2022-08-15 09:12
Ubuntu is rolling out the LTS->LTS upgrade this month, prompting the bulk of its userbase to install 22.04. This time around staying off of Wayland is even more difficult, most people will default to it.
While waynergy works as a client, any Wayland-capable server is needed about now.
A great opportunity for input-leap to distinguish itself from barrier ;)

Just threw $20 at the [bounty](https://www.bountysource.com/issues/61664045-wayland-support). Any way to help this further? (my coding time is too limited)
I'll try rkvm again in the next few days, but my previous attempt was unsuccessful.

**Comment by p12tic** [comment] 2023-01-21 07:34
Wayland support has been merged to InputLeap today in https://github.com/input-leap/input-leap/pull/1594. It still requires custom builds of mutter, libportal, xdg-desktop-portal and xdg-desktop-portal-gnome, so the code is not directly useful to the end users just yet. Thanks a lot to @whot and @ofourdan for making this happen.

**Comment by p12tic** [comment] 2023-01-21 07:41
Closing this issue as a duplicate of https://github.com/input-leap/input-leap/issues/109.

**Closed by p12tic** 2023-01-21 07:41 UTC

**Comment by neofeo** [comment] 2023-11-07 15:26
> Ubuntu is rolling out the LTS->LTS upgrade this month, prompting the bulk of its userbase to install 22.04. This time around staying off of Wayland is even more difficult, most people will default to it. While waynergy works as a client, any Wayland-capable server is needed about now. A great opportunity for input-leap to distinguish itself from barrier ;)
> 
> Just threw $20 at the [bounty](https://www.bountysource.com/issues/61664045-wayland-support). Any way to help this further? (my coding time is too limited) I'll try rkvm again in the next few days, but my previous attempt was unsuccessful.

Where those changes on those components upstreamed at some point ?

**Comment by ccoenen** [comment] 2023-11-07 18:14
There is no reasonable "upstream" any longer. Nobody maintains barrier. From what I could gather, input-leap is the only reasonable chance at an active fork right now.

Of course there's also always Symless, but I wouldn't hold my breath for them to come forward with a solution first.

**Comment by neofeo** [comment] 2023-11-07 18:15
I am talking about the patches for their respective git repos....

**Comment by neofeo** [comment] 2023-11-07 18:16
Mutter, etc

**Comment by shymega** [comment] 2023-11-10 23:51
Symless have already started talking about `libei`, but didn't really recognise the efforts that originated with this project. I daresay they'll use `libei`. This is the nature of open source.

With regards to upstream patches for the components needed, this is a good listing: https://gitlab.freedesktop.org/libinput/libei/-/issues/1
