### ISSUE TITLE
Unable to disable clipboard sharing

### ISSUE THREAD

**Issue by 9001** [input-leap/input-leap#1789] opened 2023-11-24 17:34 UTC
### What happened?

I have tried to disable clipboard sharing both through the UI, and by manually editing the config file. Regardless, the checkbox will be re-enabled the next time I visit the settings, and the feature is indeed enabled. The same applies to "max clipboard sharing size", which always returns to 1000000.

I first noticed this after migrating from Barrier 2.4.0 to Input Leap 2.4.0-20230918-git004a54fb (due to upgrading from Fedora 38 to 39); this may have been an issue with Barrier 2.4.0 as well, in which case I just never noticed :)

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

3e681454

### If applicable, where did you install Input Leap from?

The issue is observed both when building from source (latest commit as of now), and when installing from the Fedora repositories; https://fedora.pkgs.org/39/fedora-x86_64/input-leap-2.4.0%5E20230918git004a54fb-1.fc39.x86_64.rpm.html

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

X11 on the server, Windows on the client

### What OS versions are you using?

Server: Fedora 39
Client: Windows 10 LTSC (1809, 17763.4974)

**Comment by shymega** [comment] 2023-11-24 17:47
Hi, can you try building after reverting this commit: 906784c06c68e48a439a509536c92ea45d499527

I think that's the cause.

**Comment by 9001** [comment] 2023-11-24 17:56
Thanks for the quick response, and for looking into this :)

I tried reverting the commit, but it doesn't seem to have affected much.

This bug does also occur with the version of InputLeap which is packaged by Fedora 39, which was built from commit 004a54fb , so I think this issue has existed for a bit longer than that.

**Comment by kkourin** [comment] 2023-12-03 09:45
I think it is because minimum of clipboard size is > 0 (ServerConfigDialogBase.ui)
```
               <property name="minimum">
                <number>1000000</number>
               </property>
```

and this code in ServerConfig.cpp:
```
size_t ServerConfig::setClipboardSharingSize(size_t size) {
    if (size) {
        setClipboardSharing(true);
    } else {
        setClipboardSharing(false);
    }
    using std::swap;
    swap (size, m_ClipboardSharingSize);
    return size;
}
```

So size is always > 0, so clipboard sharing is always set back to true.

**Comment by kkourin** [comment] 2023-12-08 02:11
> However, as soon as you visit the settings GUI and make any unrelated change at all, then clipboard-sharing will automatically be reenabled, and you'll have to exit inputleap and make the changes once again... So it looks like it does read and write the parameters to the config file, except it always writes the default values instead of the user-config?

The GUI does write `clipboardSharing`, it just doesn't write `clipboardSharingSize`. The result of the server picking up such a config is server uses `INT_MAX` for clipboard sharing size.

**Comment by shymega** [comment] 2023-12-19 23:49
This needs fixing. Do you mind making a PR? I'm a bit swamped this season, but we should have picked up on that bug before. The whole Qt/GUI setup is a bit boggling...

**Comment by prahal** [comment] 2024-02-19 20:02
@9001 can you confirm the bug is fixed and close this bug report?
The fix has been merged in December 2023.

**Comment by 9001** [comment] 2024-02-19 20:18
Oh nice! thanks for the heads up :+1: 

Happy to confirm that I'm now able to disable clipboard sharing through the GUI, and the setting does persist as expected after a restart, so that part is all good.

I noticed however that it is still impossible to specify an alternative limit for the clipboard size; no matter what value you specify in the "Max Clipboard sharing size" textarea, you can visibly see the value being reset to 1000000 just as the window closes. But I don't mind since this is a feature I will not be using :>

So feel free to close this issue! And thanks for fixing it :heart:

**Comment by shymega** [comment] 2024-02-19 20:31
Resolved, closing.

**Closed by shymega** 2024-02-19 20:31 UTC
Labels: bug, good-first-issue, help-wanted, needs-testing, platform/windows, platform/linux, work-in-progress, from/git

**Comment by kkourin** [comment] 2024-02-19 22:38
@9001 
> I noticed however that it is still impossible to specify an alternative limit for the clipboard size; no matter what value you specify in the "Max Clipboard sharing size" textarea, you can visibly see the value being reset to 1000000 just as the window closes. But I don't mind since this is a feature I will not be using :>

Are you perhaps trying values below 1000000? That is the minimum value. When I set it above that value it seems to work, but when I set it below I get the behaviour you are describing.

**Comment by 9001** [comment] 2024-02-19 22:41
wow, yeah you're right -- never imagined that would be the minimum :grimacing: I was trying 4k and 256 bytes hehe
