### ISSUE TITLE
Server never starts on Mac OS

### ISSUE THREAD

**Issue by slrgt** [input-leap/input-leap#2109] opened 2024-12-02 07:22 UTC
### What happened?

I'm using a M3 macbook pro and when i try to launch Input Leap as a server it just tries to start but never does

Here's the log

`

```
[2024-12-02T02:21:33] INFO: starting server
[2024-12-02T02:21:33] INFO: config file: /private/var/folders/dy/xvm15qjn6qzfhbljwpq00_5r0000gn/T/InputLeap.PNpIqw
[2024-12-02T02:21:33] INFO: log level: INFO
[2024-12-02T02:21:33] INFO: drag and drop enabled
[2024-12-02T02:21:33] FATAL: An error occurred: assistive devices does not trust this process, allow it in system settings.

[2024-12-02T02:21:33] ERROR: process exited with error code: 1
[2024-12-02T02:21:33] INFO: detected process not running, auto restarting

[2024-12-02T02:21:34] INFO: starting server
[2024-12-02T02:21:34] INFO: config file: /private/var/folders/dy/xvm15qjn6qzfhbljwpq00_5r0000gn/T/InputLeap.JvjOcs
[2024-12-02T02:21:34] INFO: log level: INFO
[2024-12-02T02:21:34] INFO: drag and drop enabled
[2024-12-02T02:21:34] FATAL: An error occurred: assistive devices does not trust this process, allow it in system settings.

[2024-12-02T02:21:34] ERROR: process exited with error code: 1
[2024-12-02T02:21:34] INFO: detected process not running, auto restarting

[2024-12-02T02:21:35] INFO: starting server
[2024-12-02T02:21:35] INFO: config file: /private/var/folders/dy/xvm15qjn6qzfhbljwpq00_5r0000gn/T/InputLeap.DWPsKu
[2024-12-02T02:21:35] INFO: log level: INFO
````

### Version

v3.0.2

### If applicable, where did you install Input Leap from?

github

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

15.1.1

**Comment by huajiduola2333** [comment] 2024-12-02 13:27
“What fixed the issue for me was opening the Application bundle and dragging and dropping the /Applications/InputLeap.app/Contents/MacOS/input-leap binary to System Settings > Privacy & Security > Accessability list and allowing it to control the computer.” This is a solution I found in another issue and it works for me.

**Comment by shymega** [comment] 2024-12-02 20:44
Resolved, and dupe of #2075 - please search the issue tracker in future before opening new issues.

**Closed by shymega** 2024-12-02 20:44 UTC

**Comment by slrgt** [comment] 2024-12-02 21:00
will the next update have this fixed?

**Comment by shymega** [comment] 2024-12-02 21:04
Unknown.
