### ISSUE TITLE
BUG: MacOS Command keys don't work on Client

### ISSUE THREAD

**Issue by moebis** [input-leap/input-leap#1893] opened 2024-04-02 15:08 UTC
### What happened?

When I try to use Command-C and Command-V (copy/paste) between machines, it works on the server machine (Mac Studio), but on the client MacBook machine it just outputs the letter "c" or "v", I can right-click the pop-up menus to copy/paste, so the clipboard sharing features between the machines is working. I am using a Apple Magic Keyboard with Touch ID and Numeric Keypad if that helps. But both machines are M1 Macs.

### Version

v2.0.0-RC1

### If applicable, where did you install Input Leap from?

MacPorts

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

Sonoma 14.4.1

**Comment by Tu13es** [comment] 2024-04-08 17:36
I think this might be a dupe of https://github.com/input-leap/input-leap/issues/1886.  Can you use the on-screen keyboard to see if command is actually being hit very quickly on the other machine?

**Comment by moebis** [comment] 2024-04-16 06:34
> I think this might be a dupe of #1886. Can you use the on-screen keyboard to see if command is actually being hit very quickly on the other machine?

Yes, that is exactly the problem, short key press registered while holding down the key. Sorry I already removed everything, since I can't use it if I can't use the Command keys. I would be happy to reinstall and retest when/if there is a patched version available. Thanks.

**Comment by shymega** [comment] 2024-04-16 13:22
Closing as dupe, and also as we can't reproduce on OSK.

**Closed by shymega** 2024-04-16 13:22 UTC
