### ISSUE TITLE
#1811 introduced a regression, looks like Super is always on

### ISSUE THREAD

**Issue by darkblaze69** [input-leap/input-leap#1816] opened 2024-01-14 12:48 UTC
### What happened?

In GNOME I set a shortcut to launch programs like Super+T for launching a terminal app
After https://github.com/input-leap/input-leap/pull/1811 I get a problem:

* Launch a terminal with Super+T
* terminal launched, but when I try to type in, it looks like Super is pressed and GNOME Overview is called, the text is typed in Overview instead of terminal

If reverted to previous commit, it doesn't have such problem

https://github.com/input-leap/input-leap/assets/6976920/f33b92f8-84b9-4ced-8008-7a43951c362a

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

2f1a35c

### If applicable, where did you install Input Leap from?

self-built

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland

### What OS versions are you using?

Arch Linux

**Comment by prurigro** [comment] 2024-01-15 02:53
I think this is related to https://github.com/input-leap/input-leap/issues/1725, which makes sense considering <super> is now implemented the same way as <alt>. Like <alt>, everything is fine until <super> has been pressed, and then input behaves incorrectly until either <super> has been pressed again or the cursor enters and exits the computer it was pressed for.

With <alt> it seems like every key is disabled when the issue is triggered, while with <super> it brings up the overview, enters the key and then clears the key (as though it's typing <super>$key<backspace>).

**Comment by darkblaze69** [comment] 2024-01-25 20:11
Frankly, because of this regression it's unusable, I'm forced to use pre-1811 revision.

**Comment by prurigro** [comment] 2024-01-25 20:12
If you're building from source, you can patch both this and the alt issue out:

```
diff --git a/src/lib/platform/EiKeyState.cpp b/src/lib/platform/EiKeyState.cpp
index d5a4611e..ebc7d5f0 100644
--- a/src/lib/platform/EiKeyState.cpp
+++ b/src/lib/platform/EiKeyState.cpp
@@ -139,10 +139,10 @@ std::uint32_t EiKeyState::convert_mod_mask(std::uint32_t xkb_mask) const
             barrier_mask |= (1 << kKeyModifierBitCapsLock);
         else if (strcmp(XKB_MOD_NAME_CTRL, name) == 0)
             barrier_mask |= (1 << kKeyModifierBitControl);
-        else if (strcmp(XKB_MOD_NAME_ALT, name) == 0)
-            barrier_mask |= (1 << kKeyModifierBitAlt);
-        else if (strcmp(XKB_MOD_NAME_LOGO, name) == 0)
-            barrier_mask |= (1 << kKeyModifierBitSuper);
+        // else if (strcmp(XKB_MOD_NAME_ALT, name) == 0)
+        //     barrier_mask |= (1 << kKeyModifierBitAlt);
+        // else if (strcmp(XKB_MOD_NAME_LOGO, name) == 0)
+        //     barrier_mask |= (1 << kKeyModifierBitSuper);
     }
 
     return barrier_mask;
```

**Comment by darkblaze69** [comment] 2024-01-26 14:25
@prurigro thanks, this workaround works for me.

**Comment by p12tic** [comment] 2024-01-31 03:19
Reverted the PR, closing.

**Comment by prurigro** [comment] 2024-01-31 07:47
I'd recommend keeping this open as it's the same issue for all modifiers. Once the issue is fixed you'll want the PR in place again, too (the PR is correct and isn't the problem, it just exposed the problem).

**Comment by shymega** [comment] 2024-01-31 17:26
Re-opening, as the actual changes the PR made could re-ocur in the future. What we need to do is create a tracking issue (cc: @p12tic or @shymega), and look into sane changes that resolve the original issue.

Reverting doesn't solve the issue completely. It's still possible it'll re-emerge.

**Comment by prurigro** [comment] 2024-01-31 17:53
The same issue exists for alt and control. The alt issue is arguably even worse since it disables all keys until you press it again, while control only seems to affect using the actual control key. At the same time, without this PR super doesn't work in conjunction with any other keys (and my patch to comment out both super and alt prevents alt from working with any other keys as well).

@shymega I agree that a common tracking issue would make sense- maybe tie this and https://github.com/input-leap/input-leap/issues/1725 together with the findings @wav shared here?

**Comment by karypid** [comment] 2024-02-17 16:01
I came across this due to the "windows" key not working which I reported in #1844.

I have closed that issue as it seems to me this is kept open in order to also fix all the modified keys, so the work is within this issue's scope.

**Closed** 2024-02-26 14:57 UTC
