### ISSUE TITLE
MacOS version crashes

### ISSUE THREAD

**Issue by teras** [input-leap/input-leap#1672] opened 2023-07-29 11:32 UTC
### What happened?

I tried to build input-leap from sources. I followed the guidelines in order to compile the application from sources, using homebrew as tool provider. I tried both; release and debug builds to be sure.

Unfortunately the application crashes with a `InputLeap quit unexpectedly.` error.

The report window provides more low level information, in case it is useful. 

Also I am using an M2 MacMini pro with all latest OS patches etc.

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               input-leap [11230]
Path:                  /Users/USER/*/InputLeap.app/Contents/MacOS/input-leap
Identifier:            input-leap
Version:               2.4.0-release (2.4.0-release)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-07-29 14:28:53.0732 +0300
OS Version:            macOS 13.5 (22G74)
Report Version:        12
Anonymous UUID:        A38BE716-A739-47CC-A32C-AE6CD9B97183


Time Awake Since Boot: 1500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x0000000100b54000
Exception Codes:       0x0000000000000032, 0x0000000100b54000

Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page

VM Region Info: 0x100b54000 is in 0x100b54000-0x1010d8000;  bytes after start: 0  bytes before end: 5783551
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      dyld private memory         100b50000-100b54000    [   16K] ---/--- SM=NUL  
--->  mapped file                 100b54000-1010d8000    [ 5648K] r--/rwx SM=COW  ...t_id=a8c4be4b
      GAP OF 0x6a7ac000 BYTES
      Stack Guard                 16b884000-16f088000    [ 56.0M] ---/rwx SM=NUL  

Thread 0 Crashed:
0   dyld                          	       0x192fc0034 dyld3::MachOFile::hasMachOMagic() const + 0
1   dyld                          	       0x192f96cf8 dyld4::SyscallDelegate::mapFileReadOnly(Diagnostics&, char const*, unsigned long*, dyld4::FileID*, bool*, char*) const + 228
2   dyld                          	       0x192f96660 dyld4::SyscallDelegate::withReadOnlyMappedFile(Diagnostics&, char const*, bool, void (void const*, unsigned long, bool, dyld4::FileID const&, char const*) block_pointer) const + 88
3   dyld                          	       0x192f8f694 dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*) + 208
4   dyld                          	       0x192f8640c invocation function for block in dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&) + 1680
5   dyld                          	       0x192f85504 dyld4::Loader::forEachResolvedAtPathVar(dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, dyld4::ProcessConfig::PathOverrides::Type, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) + 184
6   dyld                          	       0x192f72f54 dyld4::ProcessConfig::PathOverrides::forEachPathVariant(char const*, dyld3::Platform, bool, bool, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) const + 488
7   dyld                          	       0x192f8528c dyld4::Loader::forEachPath(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) + 248
8   dyld                          	       0x192f859e0 dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&) + 588
9   dyld                          	       0x192f8d730 invocation function for block in dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&) + 412
10  dyld                          	       0x192fc07e8 invocation function for block in dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const + 148
11  dyld                          	       0x192f6c2d8 dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 296
12  dyld                          	       0x192fc0630 dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const + 172
13  dyld                          	       0x192f8d478 dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&) + 164
14  dyld                          	       0x192f70a0c dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 1236
15  dyld                          	       0x192f6fe18 start + 1964


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000100b54000   x1: 0x0000000000000000   x2: 0x000000016f881c18   x3: 0x0000000000040002
    x4: 0x0000000000000003   x5: 0x0000000000000000   x6: 0x000000016f881c18   x7: 0x0000000000000b80
    x8: 0x000000016f881ab0   x9: 0x000000016f881ab8  x10: 0x0000000001000010  x11: 0x0000000000000001
   x12: 0x000000016f882242  x13: 0x0000000000000000  x14: 0x0000000234958b82  x15: 0x0000000000000000
   x16: 0x000000000000005c  x17: 0x0000000192f6df60  x18: 0x0000000000000000  x19: 0x000000016f882140
   x20: 0x0000000000000003  x21: 0x000000016f881bef  x22: 0x0000000100b54000  x23: 0x000000016f881c18
   x24: 0x000000016f881bf0  x25: 0x000000016f881c10  x26: 0x000000016f8820b0  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016f881bd0   lr: 0x0000000192f96cf8
    sp: 0x000000016f881ab0   pc: 0x0000000192fc0034 cpsr: 0x80001000
   far: 0x0000000100b54000  esr: 0x92000007 (Data Abort) byte read Translation fault

Binary Images:
       0x10057c000 -        0x1008d7fff input-leap (2.4.0-release) <41171828-ce20-399f-914a-918d56c41a22> /Users/USER/*/InputLeap.app/Contents/MacOS/input-leap
       0x192f6a000 -        0x192ff8587 dyld (*) <e7a99595-e0f8-34af-be8b-9347d0d658a4> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=808.0M resident=0K(0%) swapped_out_or_unallocated=808.0M(100%)
Writable regions: Total=8448K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8448K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
__DATA                              59K        3 
__DATA_CONST                       358K        2 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       804.1M        2 
__TEXT                            4012K        2 
dyld private memory                272K        2 
mapped file                       5648K        1 
===========                     =======  ======= 
TOTAL                            878.2M       15 



-----------
Full Report
-----------

{"app_name":"input-leap","timestamp":"2023-07-29 14:28:53.00 +0300","app_version":"2.4.0-release","slice_uuid":"41171828-ce20-399f-914a-918d56c41a22","build_version":"2.4.0-release","platform":1,"bundleID":"input-leap","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.5 (22G74)","roots_installed":0,"name":"input-leap","incident_id":"4ADEE7DB-6F18-4049-A174-A8513B0BDA33"}
{
  "uptime" : 1500,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,12",
  "coalitionID" : 1304,
  "osVersion" : {
    "train" : "macOS 13.5",
    "build" : "22G74",
    "releaseType" : "User"
  },
  "captureTime" : "2023-07-29 14:28:53.0732 +0300",
  "incident" : "4ADEE7DB-6F18-4049-A174-A8513B0BDA33",
  "pid" : 11230,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-07-29 14:28:53.0519 +0300",
  "procStartAbsTime" : 36491855264,
  "procExitAbsTime" : 36492219125,
  "procName" : "input-leap",
  "procPath" : "\/Users\/USER\/*\/InputLeap.app\/Contents\/MacOS\/input-leap",
  "bundleInfo" : {"CFBundleShortVersionString":"2.4.0-release","CFBundleVersion":"2.4.0-release","CFBundleIdentifier":"input-leap"},
  "storeInfo" : {"deviceIdentifierForVendor":"348A9281-3AD1-5D73-B1AF-D2B529B946CA","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "input-leap",
  "crashReporterKey" : "A38BE716-A739-47CC-A32C-AE6CD9B97183",
  "codeSigningID" : "input-leap",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 587334144,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "sip" : "enabled",
  "vmRegionInfo" : "0x100b54000 is in 0x100b54000-0x1010d8000;  bytes after start: 0  bytes before end: 5783551\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      dyld private memory         100b50000-100b54000    [   16K] ---\/--- SM=NUL  \n--->  mapped file                 100b54000-1010d8000    [ 5648K] r--\/rwx SM=COW  ...t_id=a8c4be4b\n      GAP OF 0x6a7ac000 BYTES\n      Stack Guard                 16b884000-16f088000    [ 56.0M] ---\/rwx SM=NUL  ",
  "exception" : {"codes":"0x0000000000000032, 0x0000000100b54000","rawCodes":[50,4306845696],"type":"EXC_BAD_ACCESS","signal":"SIGKILL (Code Signature Invalid)","subtype":"UNKNOWN_0x32 at 0x0000000100b54000"},
  "termination" : {"flags":0,"code":2,"namespace":"CODESIGNING","indicator":"Invalid Page"},
  "vmregioninfo" : "0x100b54000 is in 0x100b54000-0x1010d8000;  bytes after start: 0  bytes before end: 5783551\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      dyld private memory         100b50000-100b54000    [   16K] ---\/--- SM=NUL  \n--->  mapped file                 100b54000-1010d8000    [ 5648K] r--\/rwx SM=COW  ...t_id=a8c4be4b\n      GAP OF 0x6a7ac000 BYTES\n      Stack Guard                 16b884000-16f088000    [ 56.0M] ---\/rwx SM=NUL  ",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":59385,"threadState":{"x":[{"value":4306845696},{"value":0},{"value":6166158360},{"value":262146},{"value":3},{"value":0},{"value":6166158360},{"value":2944},{"value":6166158000},{"value":6166158008},{"value":16777232},{"value":1},{"value":6166159938},{"value":0},{"value":9472150402},{"value":0},{"value":92},{"value":6760619872,"symbolLocation":56,"symbol":"fcntl"},{"value":0},{"value":6166159680},{"value":3},{"value":6166158319},{"value":4306845696},{"value":6166158360},{"value":6166158320},{"value":6166158352},{"value":6166159536},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6760787192},"cpsr":{"value":2147487744},"fp":{"value":6166158288},"sp":{"value":6166158000},"esr":{"value":2449473543,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":6760955956,"matchesCrashFrame":1},"far":{"value":4306845696}},"frames":[{"imageOffset":352308,"symbol":"dyld3::MachOFile::hasMachOMagic() const","symbolLocation":0,"imageIndex":1},{"imageOffset":183544,"symbol":"dyld4::SyscallDelegate::mapFileReadOnly(Diagnostics&, char const*, unsigned long*, dyld4::FileID*, bool*, char*) const","symbolLocation":228,"imageIndex":1},{"imageOffset":181856,"symbol":"dyld4::SyscallDelegate::withReadOnlyMappedFile(Diagnostics&, char const*, bool, void (void const*, unsigned long, bool, dyld4::FileID const&, char const*) block_pointer) const","symbolLocation":88,"imageIndex":1},{"imageOffset":153236,"symbol":"dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*)","symbolLocation":208,"imageIndex":1},{"imageOffset":115724,"symbol":"invocation function for block in dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&)","symbolLocation":1680,"imageIndex":1},{"imageOffset":111876,"symbol":"dyld4::Loader::forEachResolvedAtPathVar(dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, dyld4::ProcessConfig::PathOverrides::Type, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer)","symbolLocation":184,"imageIndex":1},{"imageOffset":36692,"symbol":"dyld4::ProcessConfig::PathOverrides::forEachPathVariant(char const*, dyld3::Platform, bool, bool, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) const","symbolLocation":488,"imageIndex":1},{"imageOffset":111244,"symbol":"dyld4::Loader::forEachPath(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer)","symbolLocation":248,"imageIndex":1},{"imageOffset":113120,"symbol":"dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&)","symbolLocation":588,"imageIndex":1},{"imageOffset":145200,"symbol":"invocation function for block in dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&)","symbolLocation":412,"imageIndex":1},{"imageOffset":354280,"symbol":"invocation function for block in dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":148,"imageIndex":1},{"imageOffset":8920,"symbol":"dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const","symbolLocation":296,"imageIndex":1},{"imageOffset":353840,"symbol":"dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":172,"imageIndex":1},{"imageOffset":144504,"symbol":"dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&)","symbolLocation":164,"imageIndex":1},{"imageOffset":27148,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":1236,"imageIndex":1},{"imageOffset":24088,"symbol":"start","symbolLocation":1964,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4300718080,
    "CFBundleShortVersionString" : "2.4.0-release",
    "CFBundleIdentifier" : "input-leap",
    "size" : 3522560,
    "uuid" : "41171828-ce20-399f-914a-918d56c41a22",
    "path" : "\/Users\/USER\/*\/InputLeap.app\/Contents\/MacOS\/input-leap",
    "name" : "input-leap",
    "CFBundleVersion" : "2.4.0-release"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6760603648,
    "size" : 583048,
    "uuid" : "e7a99595-e0f8-34af-be8b-9347d0d658a4",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6759940096,
  "size" : 3553361920,
  "uuid" : "9c875b0a-d532-3933-b1f0-f1ea72cedde2"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=808.0M resident=0K(0%) swapped_out_or_unallocated=808.0M(100%)\nWritable regions: Total=8448K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8448K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \n__DATA                              59K        3 \n__DATA_CONST                       358K        2 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       804.1M        2 \n__TEXT                            4012K        2 \ndyld private memory                272K        2 \nmapped file                       5648K        1 \n===========                     =======  ======= \nTOTAL                            878.2M       15 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "c5607c9513e1c85adf8c420a9e389d32f911449e",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112d17137f5d11121dcd4e2",
      "factorPackIds" : {

      },
      "deploymentId" : 240000329
    },
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {

      },
      "deploymentId" : 240000002
    }
  ],
  "experiments" : [

  ]
}
}

Model: Mac14,12, BootROM 8422.141.2, proc 10:6:4 processors, 16 GB, SMC 
Graphics: Apple M2 Pro, Apple M2 Pro, Built-In
Display: LG HDR 4K, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4388), wl0: Jun 11 2023 06:02:28 version 23.20.95.0.40.50.92 FWID 01-da9eb52a
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.
```

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

6446288aa619133f287cf3166bc924a99d073ea2

### If applicable, where did you install Input Leap from?

compiled from sources

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### What OS versions are you using?

13.5

**Comment by zuckschwerdt** [comment] 2023-07-29 14:34
The hints are easy to overlook:
```
Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
...
Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page
```
The build is not signed and signing is required on your system. There are various workarounds to launch unsigned apps.

**Comment by zuckschwerdt** [comment] 2023-07-29 14:36
Duplicate of #1655

**Comment by shymega** [comment] 2023-07-29 14:57
Yes, this is just a code-signing error. Try using the macOS Tap. Equally, Input Leap _should not_ be used in production, from Git mainline.

Closing.

**Closed by shymega** 2023-07-29 14:57 UTC

**Comment by teras** [comment] 2023-07-29 15:06
OK I didn't see the closed issue. Sorry for the noise. Maybe put some information about it in the [documentation](https://github.com/input-leap/input-leap/wiki/Building-on-macOS)?

Which macOS Tap are you referring to? I can't see mentioning any brew tap, if this is what you mean.

**Comment by shymega** [comment] 2023-07-29 23:31
The wiki can be edited with the [wiki-prs](https://github.com/input-leap/wiki-prs) repository - if you wanted to make a PR... I don't have much time now.

There was a discussion about it on this repository - https://github.com/input-leap/input-leap/discussions/1623.

This may work for you, it may not. But Input Leap is not ready to be used in production.
