### ISSUE TITLE
Issue with incorrect input when using Caps Lock in Korean

### ISSUE THREAD

**Issue by sinuku** [input-leap/input-leap#2132] opened 2024-12-19 01:33 UTC
### What happened?

I am currently using an Ubuntu 22.04 PC as the server and a Windows 11 PC as the client.
When typing in Korean with Caps Lock enabled, the input behaves abnormally.
Korean characters are split into consonants and vowels, as shown below:

Normal: 안녕하세요
Abnormal: ㅇㅏㄴㄴㅕㅇㅎㅏㅅㅔㅇㅛ
When Caps Lock is turned off, everything works as expected.

I came across the following issue: #870 
Do you know when this bug is scheduled to be fixed?

### Version

v3.0.1

### If applicable, where did you install Input Leap from?

[InputLeap_3.0.1_ubuntu_22-04_amd64.deb](https://github.com/input-leap/input-leap/releases/download/v3.0.1/InputLeap_3.0.1_ubuntu_22-04_amd64.deb)
[InputLeap_3.0.1_windows_qt6.exe](https://github.com/input-leap/input-leap/releases/download/v3.0.1/InputLeap_3.0.1_windows_qt6.exe)

### What OSes are you seeing the problem on? (Check all that apply)

Linux, Windows

### If applicable, are you using Wayland or X11?

X11

### What OS versions are you using?

server : Ubuntu 22.04
client : Windows 11

**Comment by shymega** [comment] 2024-12-24 19:27
Duplicate of #870, kindly do not open duplicate bugs.

**Closed by shymega** 2024-12-24 19:27 UTC
